# Generated by Django 4.2.21 on 2025-06-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa kategorii')),
                ('opis', models.TextField(blank=True, verbose_name='Opis kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa mebla')),
                ('material', models.CharField(choices=[('drewno', 'Drewno'), ('metal', 'Metal'), ('plastik', 'Plastik'), ('szklo', 'Szkło'), ('tkanina', 'Tkanina'), ('skora', 'Skóra')], max_length=20, verbose_name='Materiał')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (PLN)')),
                ('wysokosc', models.PositiveIntegerField(verbose_name='Wysokość (cm)')),
                ('szerokosc', models.PositiveIntegerField(verbose_name='Szerokość (cm)')),
                ('glebokosc', models.PositiveIntegerField(verbose_name='Głębokość (cm)')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('dostepny', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('data_dodania', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meble', to='meble_app.kategoria', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Mebel',
                'verbose_name_plural': 'Meble',
                'ordering': ['-data_dodania', 'nazwa'],
            },
        ),
    ]
